#Update all the sections by editing the dat.yml file inside _data folder.

# Site settings
tittle: My Resume
url: 'https://github.com/Muthi00/Muthi00.github,id'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/alembic'

description: A beaituful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve, Just choose one of the options.
three_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if don't want a color for chrome mobile searchbar

# Tracker
analyticts: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  
  # Build settings
  compress-site: yes
  
  encoding: "utf-8"
  compress_html: # - http://jch.penibelst.de/
    clippings: all
    ignore:
